### ISSUE TITLE
middleware order counter intuitive

### ISSUE THREAD

**Issue by the-eater** [jerowork/slim-route-attribute-provider#2]
So I'm not sure this is meant to directly reflect how Slim does it, so I'm making an issue before PR :sweat_smile: 

but I am used to middleware being executed in order it's represented in the array, however currently this happens in reverse if I have e.g.

```php
class X {
  #[Route("/", middleware: [A::class, B::class, C::class])
  public function aaa() {}
}
```

I expected the flow to be

```
A enter
B enter 
C enter
handler
C leave
B leave
A leave
```

however currently it is

```
C enter
B enter 
A enter
handler
A leave
B leave
C leave
```

this feels counter intuitive to me, but maybe it was a design decision?

**Comment by jerowork** [comment]
I did notice this in the Slim configuration indeed, when you just add middleware to a Slim app the default way. Don't like it either. 
Cannot really find an issue at slim/slim, so indeed it is a good option, to flip it so that it is more intuitive. Gonna run some tests with Slim :)

**Comment by the-eater** [comment]
nice! thanks :)
