### ISSUE TITLE
Route groups

### ISSUE THREAD

**Issue by odan** [jerowork/slim-route-attribute-provider#7]
Hi! I would like to ask how to define a route group and other nested route groups.
I am also interested in how to give a name to a route?

**Comment by jerowork** [comment]
Hello!

As this library depends on PHP8 attributes on a method level, its about defining single routes with `#[Route]` (see examples https://github.com/jerowork/route-attribute-provider#usage). Route groups are therefore not implemented.

There could be a case where route groups would make sense; when you have a class with multiple methods (and therefore multiple routes), then a route group could be defined on class level. This is not implemented (yet) as (for me) the use case never occurred. I do like the 'one route per class' idea.

A hybrid solution; using route groups the standard way, besides this library is also possible.

Naming a route is possible, see the examples: https://github.com/jerowork/route-attribute-provider#usage

**Comment by odan** [comment]
Ok, thanks for your feedback.
